import turtle
w= turtle.Screen()
w.bgcolor("darkcyan")

alexa=turtle.Turtle()
alexa.color("white")
alexa.pensize(2)
siri=turtle.Turtle()
siri.pensize(2)
siri.color("white")
prem=turtle.Turtle()
prema=turtle.Turtle()
prema.color("indianred")
prem.color("indianred")
prem.pensize(2)
prema.pensize(2)
prem.left(90)
prema.left(90)
siri.right(180)
alexa.left(30)
siri.right(30)
alexa.forward(100)
siri.forward(100)
alexa.left(90)
siri.right(90)
alexa.forward(150)
siri.forward(150)
alexa.left(120)
siri.right(120)
alexa.forward(200)
siri.forward(200)
alexa.left(90)
siri.right(90)
alexa.forward(70)
siri.forward(70)
alexa.right(60)
siri.left(60)
alexa.forward(130)
siri.forward(130)
alexa.right(90)
siri.left(90)
alexa.forward(300)
siri.forward(300)
alexa.right(90)
alexa.forward(400)
alexa.right(90)
alexa.forward(600)
siri.left(90)
siri.forward(400)
alexa.forward(10)
siri.left(90)
siri.forward(5)
alexa.forward(10)
siri.forward(10)
alexa.forward(10)
siri.forward(10)
alexa.left(90)
siri.right(90)



for i in range(210):
    prem.right(1)
    prema.left(1)
    prem.forward(1)
    prema.forward(1)
prema.left(5)
prem.right(5)
prema.forward(190)
prem.forward(190)
pran=turtle.Turtle()
pran.color("indianred")
pran.pensize(2)
pran.left(90)
pran.forward(160)
w.exitonclick()
